services:
  authentik:
    image: ghcr.io/goauthentik/server:2024.6
    container_name: authentik-server
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_DB_PASSWORD}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    volumes:
      - media:/media
      - templates:/templates
    ports:
      - "${AUTHENTIK_PORT}:9000"
    depends_on:
      - authentik-db
      - authentik-redis
    restart: unless-stopped
    networks:
      - default
      - homelab

  authentik-worker:
    image: ghcr.io/goauthentik/server:2024.6
    container_name: authentik-worker
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_DB_PASSWORD}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    volumes:
      - media:/media
      - templates:/templates
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - authentik-db
      - authentik-redis
    networks:
      - default
      - homelab

  authentik-db:
    image: postgres:16
    environment:
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: ${AUTHENTIK_DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  authentik-redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

volumes:
  media:
  templates:
  db:

networks:
  homelab:
    external: true
